In [3]:
import torch as tc
x = tc.rand(4,4)
print(x[:, 1])


tensor([0.8476, 0.1241, 0.4007, 0.7329])


In [8]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
y = x + 2
print(y.grad_fn)

In [11]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
print(torch.rand(4))

tensor([0.5789, 0.0937, 0.6792, 0.8928])


In [2]:
import matplotlib.pyplot as plt
plt.plot([0,1,2,3],[0,2,4,6])
plt.show()